import React from 'react';
import Head from 'next/head';

interface LayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body style={bodyStyle}>
      <main style={mainStyle}>{children}</main>
      
      </body>
    </html>
  );
};
const bodyStyle: React.CSSProperties = {
  margin: 0,
  display: 'flex',
  flexDirection: 'column',
  minHeight: '100vh',
};
const headerStyle: React.CSSProperties = {
  padding: '10px',
  backgroundColor: '#9C284C',
  color: 'white',
  textAlign: 'center',
};
const mainStyle: React.CSSProperties = {
  flex: 1,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  padding: '20px',
};
const footerStyle: React.CSSProperties = {
  padding: '10px',
  backgroundColor: '#9C284C',
  color: 'white',
  textAlign: 'center',
};
export default RootLayout;